camel.main.tracing=true
quarkus.application.name=file-route-builder
quarkus.otel.metrics.enabled=true
quarkus.otel.logs.enabled=true
quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317
quarkus.camel.opentelemetry.exclude-patterns=log:*
quarkus.camel.opentelemetry.trace-processors=true
